version: '3'

services:
  api:
    container_name: node
    build:
      context: ./api/
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - $API_PORT:$API_PORT

  frontend:
    container_name: react
    build:
      context: ./frontend/
      dockerfile: Dockerfile-dev
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: $NODE_ENV
