version: '3'

services:
  api:
    container_name: api
    build:
      context: ./api/
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - $API_PORT:$API_PORT
    environment:
      NODE_ENV: production
      API_PORT: $API_PORT

  frontend:
    container_name: react
    build:
      context: ./frontend/
      dockerfile: Dockerfile-prod
      args:
        NODE_ENV: production
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      NODE_ENV: production
    ports:
      - 80:80
    depends_on:
      - api
